### ISSUE TITLE
Tlačítko pro přidání produktu do košíku

### ISSUE THREAD

**Issue by Barvoj** [czcodecamp/kosik#1]
Přidat tlačítko (odkaz) na přidání produktu do košíku.

Několik bodů o kterých jsme se bavili:
- toto tlačítko bude v detailu produktu a ve výpisu produktů u každého produktu.
- bude odkazovat na akci CartControlleru
- pokud uživatel ještě nemá vytvořený košík, tak se vytvoří nový
- produkt se přidá do košíku nebo se jen inkrementuje atribut quantity, pokud už produkt v košíku je.

**Comment by JanSuchanek** [comment]
Dneska přidám i přidávání z detailu položky pokud si to ještě nedělal, ať už něco je, na tu skladovost budeš řešit i ty rezervace nebo skladovost se bude měnit až po odeslání objednávky?

Myslim si že jakmile děláme objednávku tak by se to mohlo brát jako rezervace ne? Nebo jsem to špatně pochopil.

**Comment by Barvoj** [comment]
Rezervace bych neřešil. Až při odeslání objednávky bych odečetl počet kusů ze skladu. Pokud těch kůsu na skladu nebude dostatek, tak bych proste zobrazil že nejsou na sklade a že očekáváme doručení tehdy a tehdy..

**Comment by JanSuchanek** [comment]
Ok
